export let initialState = {
	"form": {
		"residences": [],
		"previous_ssns": [],
		"person": {
			"work_phone": '',
			"student_status": '',
			"state_of_birth": '',
			"ssn": '',
			"race": '',
			"occupation": '',
			"middle_name": '',
			"marital_status": '',
			"mailing_address_id": '',
			"last_name": '',
			"home_phone": '',
			"gender": '',
			"first_name": '',
			"ethnicity": '',
			"email": '',
			"driver_license_state": '',
			"driver_license_number": '',
			"driver_license_exp_date": '',
			"dob": '',
			"country_of_birth": '',
			"city_of_birth": '',
			"citizenship": '',
			"cell_phone": ''
		},
		"incomes": [],
		"housing_forms": [],
		"household_members": [],
		"employments": [],
		"criminal_histories": [],
		"aliases": [],
		"addresses": [],
		"contacts": []
	},
	"buildings": []
};

export let models = {
	"Residence": {
		"id": '',
		"start_date": '',
		"reason": '',
		"landlord": {
			"work_phone": '',
			"student_status": '',
			"state_of_birth": '',
			"ssn": '',
			"race": '',
			"occupation": '',
			"middle_name": '',
			"marital_status": '',
			"mailing_address_id": '',
			"last_name": '',
			"home_phone": '',
			"gender": '',
			"first_name": '',
			"ethnicity": '',
			"email": '',
			"driver_license_state": '',
			"driver_license_number": '',
			"driver_license_exp_date": '',
			"dob": '',
			"country_of_birth": '',
			"city_of_birth": '',
			"citizenship": '',
			"cell_phone": '',
			"address": {
				"street": '',
				"state": '',
				"city": '',
				"zip": '',
				"apt": ''
			}
		},
		"end_date": '',
		"current": false,
		"address_id": ''
	},
	"PreviousSSN": {
		"id": '',
		"previous_number": ''
	},
	"Person": {
		"work_phone": '',
		"student_status": '',
		"state_of_birth": '',
		"ssn": '',
		"race": '',
		"occupation": '',
		"middle_name": '',
		"marital_status": '',
		"mailing_address_id": '',
		"last_name": '',
		"home_phone": '',
		"gender": '',
		"first_name": '',
		"ethnicity": '',
		"email": '',
		"driver_license_state": '',
		"driver_license_number": '',
		"driver_license_exp_date": '',
		"dob": '',
		"country_of_birth": '',
		"city_of_birth": '',
		"citizenship": '',
		"cell_phone": ''
	},
	"Income": {
		"id": '',
		"interval": '',
		"income_type": '',
		"amount": ''
	},
	"HousingForm": {
		"waitlist_open": null,
		"waitlist_closed_until": null,
		"wait_length": null,
		"utilities_included": "",
		"required_proofs": {
			"social_security_card": null,
			"rental_history": null,
			"other": null,
			"none": null,
			"income": null,
			"identification": null,
			"employment_history": null,
			"disability": null,
			"dc_residency": null,
			"citizenship": null,
			"birth_certificate": null,
			"bank_statement": null
		},
		"pets_allowed": "",
		"notes": "",
		"name": "",
		"longitude": null,
		"latitude": null,
		"id": null,
		"eligibility": {
			"mobility_impairment": null,
			"minimum_age_without_disability": null,
			"minimum_age_with_disability": null,
			"income": null,
			"elderly": null,
			"disability": null
		},
		"company_phone": "",
		"company_name": "",
		"bus_routes": "",
		"building_phone": "",
		"bedrooms_open": "",
		"bedrooms_offered": "",
		"application_on_file": null,
		"application_info": "",
		"application_fee": null,
		"address": ""
	},
	"HouseholdMember": {
		"id": '',
		"relationship": '',
		"member": {
			"work_phone": '',
			"student_status": '',
			"state_of_birth": '',
			"ssn": '',
			"race": '',
			"occupation": '',
			"middle_name": '',
			"marital_status": '',
			"mailing_address_id": '',
			"last_name": '',
			"home_phone": '',
			"gender": '',
			"first_name": '',
			"ethnicity": '',
			"email": '',
			"driver_license_state": '',
			"driver_license_number": '',
			"driver_license_exp_date": '',
			"dob": '',
			"country_of_birth": '',
			"city_of_birth": '',
			"citizenship": '',
			"cell_phone": ''
		}
	},
	"Employment": {
		"id": '',
		"supervisor_name": '',
		"start_date": '',
		"position": '',
		"phone": '',
		"part_time": false,
		"end_date": '',
		"employer_name": '',
		"current": false,
		"address": {
			"street": '',
			"state": '',
			"id": '',
			"city": '',
			"zip": '',
			"apt": ''
		}
	},
	"CriminalHistory": {
		"id": '',
		"year": '',
		"description": '',
		"state": '',
		"crime_type": ''
	},
	"Alias": {
		"id": '',
		"name": ''
	},
	"Address": {
		"id": '',
		"street": '',
		"state": '',
		"id": '',
		"city": '',
		"apt": '',
		"zip": '',
		"residence": false
	},
	"Contact": {
		"id": '',
		"work_phone": '',
		"last_name": '',
		"home_phone": '',
		"first_name": '',
		"relationship": '',
		"cell_phone": '',
		"address": {
			"street": '',
			"state": '',
			"city": '',
			"zip": '',
			"apt": ''
		}
	}
};
