export let initialState = {
	"residences": [],
	"previous_ssns": [],
	"person": {
		"work_phone": '',
		"student_status": '',
		"state_of_birth": '',
		"ssn": '',
		"race": '',
		"occupation": '',
		"middle_name": '',
		"marital_status": '',
		"mailing_address_id": '',
		"last_name": '',
		"home_phone": '',
		"gender": '',
		"first_name": '',
		"ethnicity": '',
		"email": '',
		"driver_license_state": '',
		"driver_license_number": '',
		"driver_license_exp_date": '',
		"dob": '',
		"country_of_birth": '',
		"city_of_birth": '',
		"citizenship": '',
		"cell_phone": ''
	},
	"incomes": [],
	"housing_forms": [],
	"household_members": [],
	"employments": [],
	"criminal_histories": [],
	"aliases": [],
	"addresses": []
};

export let models = {
	"Residence": {
		"id": '',
		"start_date": '',
		"reason": '',
		"landlord": {
			"work_phone": '',
			"student_status": '',
			"state_of_birth": '',
			"ssn": '',
			"race": '',
			"occupation": '',
			"middle_name": '',
			"marital_status": '',
			"mailing_address_id": '',
			"last_name": '',
			"home_phone": '',
			"gender": '',
			"first_name": '',
			"ethnicity": '',
			"email": '',
			"driver_license_state": '',
			"driver_license_number": '',
			"driver_license_exp_date": '',
			"dob": '',
			"country_of_birth": '',
			"city_of_birth": '',
			"citizenship": '',
			"cell_phone": ''
		},
		"end_date": '',
		"current": false,
		"address_id": ''
	},
	"PreviousSSN": {
		"id": '',
		"previous_number": ''
	},
	"Person": {
		"work_phone": '',
		"student_status": '',
		"state_of_birth": '',
		"ssn": '',
		"race": '',
		"occupation": '',
		"middle_name": '',
		"marital_status": '',
		"mailing_address_id": '',
		"last_name": '',
		"home_phone": '',
		"gender": '',
		"first_name": '',
		"ethnicity": '',
		"email": '',
		"driver_license_state": '',
		"driver_license_number": '',
		"driver_license_exp_date": '',
		"dob": '',
		"country_of_birth": '',
		"city_of_birth": '',
		"citizenship": '',
		"cell_phone": ''
	},
	"Income": {
		"id": '',
		"interval": '',
		"income_type": '',
		"amount": ''
	},
	"HousingForm": "",
	"HouseholdMember": {
		"id": '',
		"relationship": '',
		"member": {
			"work_phone": '',
			"student_status": '',
			"state_of_birth": '',
			"ssn": '',
			"race": '',
			"occupation": '',
			"middle_name": '',
			"marital_status": '',
			"mailing_address_id": '',
			"last_name": '',
			"home_phone": '',
			"gender": '',
			"first_name": '',
			"ethnicity": '',
			"email": '',
			"driver_license_state": '',
			"driver_license_number": '',
			"driver_license_exp_date": '',
			"dob": '',
			"country_of_birth": '',
			"city_of_birth": '',
			"citizenship": '',
			"cell_phone": ''
		}
	},
	"Employment": {
		"id": '',
		"supervisor_name": '',
		"start_date": '',
		"position": '',
		"phone": '',
		"part_time": false,
		"end_date": '',
		"employer_name": '',
		"current": false,
		"address": {
			"street": '',
			"state": '',
			"id": '',
			"city": '',
			"apt": ''
		}
	},
	"CriminalHistory": {
		"id": '',
		"year": '',
		"description": '',
		"crime_type": ''
	},
	"Alias": {
		"id": '',
		"name": ''
	},
	"Address": {
		"id": '',
		"street": '',
		"state": '',
		"id": '',
		"city": '',
		"apt": '',
		"residence": false
	}
};
